apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  annotations:
    volume.beta.kubernetes.io/storage-class: gp2
spec:
  storageClassName: aws-ebs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi