apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: database
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cHc=  # Base64 encoded value of 'pw'
  MYSQL_USER: cm9vdA==      # Base64 encoded value of 'root'
  DBPWD: cHc=  # Base64 encoded value of 'pw'
  DBUSER: cm9vdA==      # Base64 encoded value of 'root'